### Récupérer toutes les personnes
GET http://localhost:8080/person

### Récupérer toutes les stations
GET http://localhost:8080/firestation

### Récupérer toutes les informations medicales
GET http://localhost:8080/medicalRecord

### Obtenir les personnes couvertes par une caserne de pompiers
GET http://localhost:8080/alert/firestation?stationNumber=1

### Obtenir les enfants à une adresse
GET http://localhost:8080/alert/childAlert?address=1509 Culver St

### Obtenir les numéros de téléphone des personnes couvertes par une caserne de pompiers
GET http://localhost:8080/alert/phoneAlert?firestation=1

### Obtenir les personnes à une adresse donnée
GET http://localhost:8080/alert/fire?address=1509 Culver St

### Obtenir tous les foyers desservis par les casernes de pompier
GET http://localhost:8080/alert/flood/stations?stations=1,2,3

### Information sur les personnes portant le même nom
GET http://localhost:8080/alert/personInfo?lastName=Boyd

### Obtenir les emails de tous les habitants d'une ville
GET http://localhost:8080/alert/communityEmail?city=Culver

### Récupérer une personne par nom
GET http://localhost:8080/person/Jamie/Peters

Accept: application/json


